### ISSUE TITLE
Losing content while translating pouchdb-upsert

### ISSUE THREAD

**Issue by Schahen** [Kotlin/dukat#109]
While translating https://github.com/DefinitelyTyped/DefinitelyTyped/blob/31929c09c7b4490f87766206b412da4a6a581dc3/types/pouchdb-upsert/index.d.ts

```bash
[shabunc@shagen demo (master)]$ dukat /Users/shabunc/.gradle//definitelyTyped/DefinitelyTyped-31929c09c7b4490f87766206b412da4a6a581dc3/types/pouchdb-upsert/index.d.ts
index.PouchDB.kt
index.PouchDB.kt
index.pouchdb_upsert.kt
```

index.PouchDB.kt is generated twice and that never suppose to happen - that actually means that file was generated and then regenerated, thus, content of the first file is just lost.

**Comment by art-solopov** [comment]
I've encountered the same error when translating https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request/index.d.ts:

```
─> dukat -d headers node_modules/@types/request/index.d.ts
request.index.request.kt
request.index.kt
request.index.request.kt
```
