### ISSUE TITLE
nothing was converted from jsbi

### ISSUE THREAD

**Issue by decafbad** [Kotlin/dukat#169]
ts2kt just says "Nothing was converted" when I tried to convert jsbi.d.ts

https://github.com/GoogleChromeLabs/jsbi/blob/master/jsbi.d.ts

**Comment by Schahen** [comment]
This issue was migrated from the `ts2kt` project which is deprecated in favour of a newer tool, `dukat`. I'm happy to announce that in dukat `jsbi.d.ts` declaration is translated and compiling.
