### ISSUE TITLE
knex.d.ts - ImportDeclaration kind unsupported

### ISSUE THREAD

**Issue by g6123** [Kotlin/dukat#184]
Hi, I'm trying to translate `knex/knex.d.ts` into `.kt` file.
And, I got the following error now.

```
Unsupported node.kind: 230, name: ImportDeclaration (testDefinitelyTyped/DefinitelyTyped/knex/knex.d.ts:9:38 to 10:34)
```

What I understood is that ts2kt does not support some subset of syntax yet, at least one in the `knex.d.ts`.
*I'd like to know what that unsupported syntax exactly is, and how can I contribute to support it.*

Here is a code snippet from `knex.d.ts`, where the error got thrown.
```
// knex.d.ts:9:38 to 10:34

  import Promise = require("bluebird");
  import * as events from "events";
```

**Comment by Schahen** [comment]
Dukat supports both of this imports however translation fails with exception, closing this one and creating separate task https://github.com/Kotlin/dukat/issues/297
