### ISSUE TITLE
Output missing imports

### ISSUE THREAD

**Issue by tristancaron** [Kotlin/dukat#186]
### Environment

- Ubuntu `16.10`
- Kotlin `1.1RC`
- yarn `0.21.3`
- ts2kt `0.0.8`
- vue `2.2.1`

### Problem

The output generated by ts2kt seems to not be usable. It's missing imports, and the IDE complains also about missing `external` keyword.

Also it adds an extra dot like `output..kt`.

### How to reproduce

In a npm/yarn project:

- Open a terminal and go to the project directory root
- `npm install ts2kt --save-dev` or `yarn add ts2kt --dev`
- `npm install vue` or `yarn add vue`
- In `package.json`, add `{"scripts":"ts2kt": "ts2kt"}`
- `mkdir ./output/path` (otherwise, it seems to not work)
- `npm run ts2kt -- -d ./output/path ./node_modules/vue/types/vue.d.ts` or `yarn run  ts2kt -- -d ./output/path ./node_modules/vue/types/vue.d.ts`

For me, I get:

Terminal output:
```zsh
tristancaron@XPS:~/IdeaProjects/myProject$ yarn run ts2kt -- -d ./src/lib/vue ./node_modules/vue/types/vue.d.ts
yarn run v0.21.3
$ "/home/tristancaron/IdeaProjects/myProject/node_modules/.bin/ts2kt" -d ./src/lib/vue ./node_modules/vue/types/vue.d.ts
Converting ./node_modules/vue/types/vue.d.ts
ts2kt: "ImportDeclaration" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:1:1 to 10:20)
ts2kt: "ImportDeclaration" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:10:20 to 11:71)
ts2kt: "ImportDeclaration" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:11:71 to 12:57)
ts2kt: "TypeQuery" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:50:8 to 50:23)
ts2kt: "TypeQuery" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:51:11 to 51:29)
ts2kt: "TypeQuery" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:81:78 to 81:89)
ts2kt: "TypeQuery" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:81:78 to 81:89)
ts2kt: "TypeQuery" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:93:73 to 93:84)
ts2kt: "TypeQuery" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:93:73 to 93:84)
ts2kt: "TypeQuery" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:96:22 to 96:33)
ts2kt: "TypeQuery" kind unsupported yet here! (node_modules/vue/types/vue.d.ts:98:26 to 98:62)
Save declarations:
        ./src/lib/vue/vue..kt
Done in 0.60s.
```

IDE errors:
![image](https://cloud.githubusercontent.com/assets/9624669/23404816/4690f4aa-fdb7-11e6-83ec-6d30639fdbf9.png)

**Comment by Schahen** [comment]
This issue was migrated from the `ts2kt` project which is deprecated in favour of a newer tool, `dukat`. 

In dukat imports of this kind are supported. Feel free to create any new issue in dukat repository if needed.
