### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by deviant-studio** [Kotlin/dukat#189]
Hello!
I'm trying to process bunch of .ts files, particularly `firebase` declarations from this repo:
https://github.com/firebase/firebase-js-sdk
I've prepared simple script:
```kotlin
class Converter {

    fun convertAll(path: String) = runBlocking {
        val root = File(path)
        println("root=${root.absolutePath}")
        File("converted").mkdirs()
        root.walk()
            .filter { file -> file.isFile && file.name.endsWith(".d.ts") }
            .asIterable()
            .map { file ->
                val dest = file.parent.replace("^\\w+[/\\\\]".toRegex(), { "converted${File.separator}" })
                println("$file -> $dest")
                val command = "cmd.exe /c ts2kt -d $dest $file"
                doJob(command)
            }
            .forEach {
                it.join()
            }
    }

    private fun doJob(command: String) = launch {
        println(command)
        val process = Runtime.getRuntime().exec(command)
        process.waitFor()
    }
}
```

it works ok, but i see lot of clashed redeclarations in generated code like 
`external interface `T$0``

`external interface `T$1``

etc
It would be nice to have batch mode in ts2kt tool that will allow to generate unique names per files pack. Someting like `ts2kt -f <folder>`

**Comment by Schahen** [comment]
This issue was migrated from the `ts2kt` project which is deprecated in favour of a newer tool, `dukat`.  In dukat you need just pass the index files and the rest will be resolved automatically.
