### ISSUE TITLE
Can't run CliKt from IDE with a d.ts file as program argument

### ISSUE THREAD

**Issue by rendner** [Kotlin/dukat#206]
Hello Shagen,

I tried to run dukat from my IDE with a path to a `d.ts` file. It seems that isn't possible because the main class `org.jetbrains.dukat.cli.CliKt` expects input on [Std::in](https://github.com/Kotlin/dukat/blob/01674ac2617f843f76ba89f29a995449f49805d9/command-line/src/org/jetbrains/dukat/cli/cli.kt#L42).

It seems this commit removed the way which I currently try to execute: [isTsTranslation](https://github.com/Kotlin/dukat/commit/7af8d678e889c5fdb72a31b39d7551e16246d0a0#diff-654d4ec9d223abd255d22ba165f959e4L282-L294).

Or did I misunderstand the documentation? I don't have any specific goal in my mind. I just want to look how `dukat` works. What would be the expected way to run `dukat` project from an IDE?

**Comment by epabst** [comment]
With dukat failing on some dependencies, I've given up (for now) on enabling it during the build of my project.  So, I'm left with running it on the command-line.  However, due to this issue I can't run the newer versions anymore using the CLI.  I have to go back to version 0.0.14!!!   Can someone please fix this?!?

**Comment by rendner** [comment]
@epabst: Thank you for the info.

It seems CliKt can't be invoked with a normal d.ts file. I tweaked the code to read my file:
```
isTsTranslation -> {
	options.sources.forEach { source ->
	    translateBinaryBundle(
		    //System.`in`.readBytes(),
		    File(source).readBytes(),
		    options.outDir,
		    moduleResolver,
		    options.reportPath,
		    options.generateDescriptors
	    )
	}
}
```
And got the following exception: 
```
Exception in thread "main" com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
```
It sounds this class now expects a protobuf message?

**Comment by Schahen** [comment]
@rendner, @epabst  I'm not sure I got the question right - so, when we are talking about typescript translation (there are some other sources but it's irrelevant) following happens behind the curtains:

- nodejs part parses typescript and converts everything to a custom binary format
- this data is pipelined to the java part which does the rest

That said, the java part is indeed of always expecting that something will be pipelined via stdout - as it already been mentioned.

From here we can choose one of following options - depending among other things on what your goals are:

- we can teach the java part of command line to read binary data passed as a file name
- you can investigate the API behind the conversion and just use it.  I will leave a message in Slack - may be it would be just faster to discuss it there.

**Comment by epabst** [comment]
Have you looked at version 0.0.14?  It works great.  It reads from the *.d.ts files specified on the command line and converts them to *.kt files.  Can't we just restore that functionality as it was before?

**Comment by epabst** [comment]
I was mistaken.  It is working.  So sorry for the confusion.  Thanks @Schahen for reaching out to me to work out my misunderstanding.

**Comment by epabst** [comment]
Please close this.

**Comment by Schahen** [comment]
I'm closing this one and introduce any file-reading changes in CLI in a separate task if needed.
