### ISSUE TITLE
Bugs and problems found by analyzing output of DescriptorTests

### ISSUE THREAD

**Issue by trilis** [Kotlin/dukat#237]
### 1. Imports from root package
There are still some cases where imports for declarations from base package are missing. Maybe it has something to do with transformations on Model level, such as merging (AFAIK we add these imports only on Node level)
See tests:
- `mergeDeclarations/moduleWith/functionAndSecondaryWithTrait`
`Fiber` should be imported from package `fibers`
-  `qualifiedNames/extendingEntityFromParentModule`
`ContextResponse` should be imported from package `Application`

### 2. Starred imports
As far as I understand, they don't work currently at all, no files and packages are created for these imports, which results in compilation errors for not found declarations.
See tests:
- `interface/inheritance/withQualifiedParent`
package `stream` is not found

### 3. FQNs
See tests:
- `extendExternalDeclarations/withGenericParams`
Here we have FQNs, but they are wrong: instead of referencing `Q.Promise`, which is correct, they all reference `<LIBROOT>.Promise` (meaning `kotlin.js.Promise`).
- `import/externalImport`
- `typescript/interface/generics/genericWithInvokeInExtended/genericWithInvokeInExtended`
`ClassLikeReferenceModel` (class for extension receivers) doesn't have FQNs, which results in some problems in descriptors. I need to somehow resolve `Static` as `SomeNamespace.Static` when I see function `Static.getVersion()`

### 4. Other not found declarations
I suppose that here dukat works as intended and we can just change tests. But maybe I am wrong and dukat should find these declarations. Please take a look at these and confirm what is the case.
See tests:
- `module/exportAssignment/exportFromExternalModule/overloadedFunctions`
package `NodeJS` is not found
- `stdlib/convertTsStdlib`
`IterableIterator` not found (we don't have one in Kotlin stdlib, right?)

**Comment by Schahen** [comment]
Thanks Alexey this is really helpful!

**Comment by Schahen** [comment]
addressed in a bunch of different separate issues
