### ISSUE TITLE
How to only or exclude library.

### ISSUE THREAD

**Issue by sakebook** [Kotlin/dukat#239]
I'm using gradle plugin. (`kotlin.js.experimental.generateKotlinExternals=true`)

Is it possible to specify the target of dukat from what is declared in dependencies?

Now, everything is target, so I want to exclude those that give errors.

**Comment by Schahen** [comment]
@sakebook unfortunately as of know you can not ((( we do realise that this is a problem and going go work on a solution. Just right now however, the best option would be to just compile *.d.ts-s manually

**Comment by sakebook** [comment]
I understood. Looking forward to being available :)

**Comment by Schahen** [comment]
Will create a separate task when we'll plan to implement this.
