### ISSUE TITLE
Method body is converted twice

### ISSUE THREAD

**Issue by Schahen** [Kotlin/dukat#291]
Following code:

```typescript
export class Pinger {
    ping() {
        println("PING!!!");
    }   
}
```

is converted as:
```kotlin
open class Pinger {
    open fun ping() { println("PING!!!") }
        println("PING!!!")
    }   
}

```

if after your latest PR this will be gone-  just close this but please don't try to fix it in the same PR if not - this deserves a separate commit )

**Comment by trilis** [comment]
Yes, this is exactly what [this commit](https://github.com/Kotlin/dukat/pull/287/commits/d6ed38336c33e61c859782824061415356bde940) fixes, so I'll close this.

**Comment by shabunc** [comment]
I suggest us to close anything only after it's in master but still great!
