### ISSUE TITLE
ClassLike can not extend nested entity

### ISSUE THREAD

**Issue by Schahen** [Kotlin/dukat#296]
I was 100% sure that this issue exist however I'm failing to find it, to lost it is worser than to have a duplicate, so, here's a minimal breaking example:

```ts
declare class Bluebird<R> implements Bluebird.Inspection<R> {
}

declare namespace Bluebird {
  interface Inspection<R> {
  }
}
external open class Bluebird<R> : Inspection<R> {
    interface Inspection<R>
}
```

which is translated to:
```kotlin
external open class Bluebird<R> : Inspection<R> {
    interface Inspection<R>
}
```
This seemingly harmless snippet of code is actually illegal in Kotlin since we can no inherit from nested entities. 

Luckily, the workaround exists and it's as easy as just move Inspection out of parent class and us JsQualifier annotation if needed.

**Comment by Schahen** [comment]
Here's how underlying javascript structure supposed to look like:

```js
class Ping {
    ping() {
        console.log("PING");
    }   
}

class Pong {
    pong() {
        console.log("PONG");
    }   
}

Ping.Pong = Pong;
exports.Ping = Ping;
```

**Comment by Schahen** [comment]
Funny thing is that I don't know how to mimic exactly this in ts, I know how to do this:

```

export declare class Ping implements Ping.Pong {
    ping();
    pong();
}

declare namespace Ping {
    interface Pong {
        pong();
    }   
}
```

but this won't if Ping would have been a class

**Comment by Schahen** [comment]
Here's more "pure" js example of such declaration
```js
function Ping() { }
Ping.Pong = function() { }

Ping.prototype = new Ping.Pong();

Ping.prototype.ping = function() {
    console.log("ping!!!");
}

Ping.Pong.prototype.pong = function() {
    console.log("pong!!!");
}

exports.Ping = Ping;
```

**Comment by Schahen** [comment]
Minimal typescript example:
```typescript
export declare class Ping implements Ping.Pong {
    ping();
    pong();
}

declare namespace Ping {
  interface Pong {
      pong();
  }
}
```

**Comment by shabunc** [comment]
I can see a lot of room for improvement but well, know we are resolving this particular situation, so I'm closing this one.
