### ISSUE TITLE
Remove redundant "definedExternally"

### ISSUE THREAD

**Issue by Schahen** [Kotlin/dukat#31]
Looks like following is true:

- When class is marked as external we don't need to assign `definedExternally` for it members
- When variable is marked as external we don't need to assign `definedExternally` as it's value.

If this two statements are correct I suggest to got rid of definedExternally completely.

**Comment by bashor** [comment]
Right rule is:
`definedExternally` is required only for non-abstract properties(val + var) of `external interface`

**Comment by ts2kt** [comment]
There are also constructor and function parameters, which can have default value or be optional.

**Comment by Schahen** [comment]
This was done actually quite ago, any further improvements will be addressed in separate issues
