### ISSUE TITLE
Global type imported instead of namespaced type leads to compilation failure

### ISSUE THREAD

**Issue by hunterwerlla** [Kotlin/dukat#342]
Using Dukat 0.5.7 and Kotlin 1.4.0-rc, generating externals for "@types/vscode":
```
    implementation(npm("@types/vscode", "1.42.0", generateExternals = true))
```
 imports the wrong type `Event`. It imports `org.w3c.dom.events.Event` but it should be importing event from [here]( https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/base/common/event.ts#L16). It properly generates `Event` from VSCode, but It's pulling in `Event` from the import `org.w3c.dom.events.*` and not adding the import for `vscode.Event`

**Comment by trilis** [comment]
Looks like this issue was resolved alongside with #379 and doesn't reproduce in master, so I'm closing this
