### ISSUE TITLE
Generate JSON report based on run results

### ISSUE THREAD

**Issue by Schahen** [Kotlin/dukat#35]
I've been asked by our tooling team to add possibility to have a json report of what happened during the run. For now it will be an undocumented cli flag and the only data I can think of so far is the list of generated entities.

However this can be a good start for introducing more complicated reports that in turn can be used in tests and or teamcity stats artifact generation.

**Comment by ts2kt** [comment]
Also would be useful to `println` to terminal name of currently converted file. For example:
```
$ dukat /path/to/file1.d.ts /path/to/file2.d.ts
Preparing...
Converting /path/to/file1.d.ts... Done
Converting /path/to/file2.d.ts... Done
```
Now when I run dukat with 350+ specified files. It takes 2 hours and all this time nothing is displayed. List of all converted files is displayed only when all files will be converted.

**Comment by Schahen** [comment]
@ts2kt  will create a separate task and take care of it. Actually it's too bad that for now it takes that much of a time (we're working on it) however in any case this won't harm.
