### ISSUE TITLE
Is dukat@next still relevant?

### ISSUE THREAD

**Issue by Vampire** [Kotlin/dukat#353]
Maybe I got something wrong, but https://www.npmjs.com/package/dukat?activeTab=versions shows
![grafik](https://user-images.githubusercontent.com/325196/89631840-9f2bbf00-d8a1-11ea-8a9f-b5f014920f62.png)
which does not match this sentence in the readme:
> On a weekly basis we also deply a dev build which sums up what we currently have in master

So it seems either the weekly build is broken, or the readme should have that sentence removed. :-)

**Comment by Schahen** [comment]
Yep, I apologize for this - for techical reasons pipeline publishing next was disabled for a while.
And new versions will be published every 2-3 days.
