### ISSUE TITLE
Publish GitHub releases

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/dukat#39]
Now that we can watch releases only, GitHub releases feature is more important. Could you fill them and ensure all future releases go this way, so we can get the notification?

**Comment by Schahen** [comment]
Sure thing, will close this issue as soon as it will happen for the first time )

**Comment by LouisCAD** [comment]
Great. Note that you can add tags for any commit in history and setup past releases too.

**Comment by Schahen** [comment]
Well today I've made the very first release via github so I'm closing this one.
