### ISSUE TITLE
Conflicting declarations generated in lib.es2018.asynciterable.module_dukat.kt

### ISSUE THREAD

**Issue by Vampire** [Kotlin/dukat#402]
Something in the combination used at https://github.com/Vampire/setup-wsl causes the file `lib.es2018.asynciterable.module_dukat.kt` to be generated.
Inside you get:
```kt
    val `return`: ((value: TReturn) -> Promise<dynamic /* IteratorYieldResult<T> | IteratorReturnResult<TReturn> */>)?
        get() = definedExternally
    val `return`: ((value: PromiseLike<TReturn>) -> Promise<dynamic /* IteratorYieldResult<T> | IteratorReturnResult<TReturn> */>)?
        get() = definedExternally
```
which are conflicting declarations that cannot compile.
As I don't use it directly anyway my solution was to delete one and make the other have `dynamic` instead of `TReturn` or `PromiseLike<TReturn>` but that is no proper fix of course.
I think it comes from this line:
```ts
    return?(value?: TReturn | PromiseLike<TReturn>): Promise<IteratorResult<T, TReturn>>;
```
from the file `build/js/node_modules/dukat/d.ts.libs/lib.es2018.asynciterable.d.ts`.

**Comment by trilis** [comment]
Hi! This look similar to #344, so #390 should fix this as well.

**Comment by Vampire** [comment]
Nice, thx
