### ISSUE TITLE
typealias with @file:JsModule() and @file:JsQualifier()

### ISSUE THREAD

**Issue by ts2kt** [Kotlin/dukat#41]
Using `typealias` in file with `@file:JsModule()` or `@file:JsQualifier()` produce errors:

`Can't put non-external declarations in file marked with JsModule annotation`
`Can't put non-external declarations in file marked with JsQualifier annotation`

related with [KT-31493](https://youtrack.jetbrains.com/issue/KT-31493)

Example: https://github.com/i18next/i18next/blob/master/index.d.ts
(there are some other problems with converting example file)

**Comment by Schahen** [comment]
Basically (apart from introducing changes to the language to allow type aliases in files with global JsModule annotation - which can be reasonable but still not something that can be done quick) it looks like we have to choose from one of following two options:

1. Move all generated entities to a separate file. 
2. Just don't put global JsModule annotation but rather mark with this annotation all top level entities. 

I need to think about both options and weigh all the outcomes and possible consequences before choosing  one if them.
