### ISSUE TITLE
Type parameters are not substituted in constructor of child classes

### ISSUE THREAD

**Issue by joffrey-bion** [Kotlin/dukat#414]
Using `0.5.8-rc.0`, I found this generics-related issue, which is similar to https://github.com/Kotlin/dukat/issues/349, but has not been fixed as part of it.

Source:
```ts
export declare abstract class Parent<T> {
  constructor(arg?: T);
}
export declare class Child extends Parent<number> {
}
```

Generated:
```kotlin
external open class Parent<T>(arg: T = definedExternally)

external open class Child(arg: T = definedExternally) : Parent<Number>
```

The type parameter `T` in the constructor of the child should have been replaced by `Number`, and instead gives a compile error.

**Comment by JSMonk** [comment]
Fixed in https://github.com/Kotlin/dukat/pull/451
