### ISSUE TITLE
Enum class in namespace is not generated in presence of class with same name as namespace

### ISSUE THREAD

**Issue by wfhartford** [Kotlin/dukat#439]
I'm trying to generate Kotlin wrapper code for typescript definitions generated by protocol buffers. Dukat consistently generated Kotlin that does not compile when a protocol buffer message has a `oneof` field. After eliminating a fair amount of unrelated code, the typescript definition code which causes the error is something like the following:
```
export class FooResponse {
  getResultCase(): FooResponse.ResultCase;
}

export namespace FooResponse {
  export enum ResultCase {
    RESULT_NOT_SET = 0,
    SUCCESS = 1,
    FAILURE = 2,
  }
}
```

When Dukat processes this file, it does not generate the `ResultCase` enum at all, but tries to import it:
```
// [annotation and standard imports redacted]
import FooResponse.ResultCase

external open class FooResponse {
    open fun getResultCase(): ResultCase
}
```

If the `FooResponse` class is not present, but the enum and namespace are, the enum will be generated.

**Comment by wfhartford** [comment]
Input `.d.ts` and output `.kt` file attached in a ZIP: [439.zip](https://github.com/Kotlin/dukat/files/6327757/439.zip)

**Comment by wfhartford** [comment]
If someone could give some advice on how to fix this issue, I'd be happy to spend some time on it. Thanks.

**Comment by JSMonk** [comment]
Fixed in https://github.com/Kotlin/dukat/pull/449
