### ISSUE TITLE
Make it possible to reference nodejs declarations as stdlib

### ISSUE THREAD

**Issue by Schahen** [Kotlin/dukat#57]
Many real-life declarations (see https://github.com/Kotlin/dukat/issues?utf8=✓&q=is%3Aissue+label%3A%22case+study%22+)  are referencing NodeJS declarations without explicitly linking nodejs definitions library. 

It seems to me that the simplest thing we can have - is to make it possible to state what is stdlib for this particular set of declarations.

**Comment by ts2kt** [comment]
Referencing not only nodejs declarations causes problems, but JS stdlib too.
For example, we may have declaration of class, which extends JS `Error` class.
Related with [KT-31487](https://youtrack.jetbrains.com/issue/KT-31487)

**Comment by Schahen** [comment]
This one is too general, all separate issues (like one mentioned by @ts2kt ) are addressed separately.
