### ISSUE TITLE
Typos in 0.10.0 GitHub release

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/dukat#59]
Here: https://github.com/Kotlin/dukat/releases/tag/v0.0.10, this:
> After all, it it the way it is supposed to he 
should be that:
> After all, it i**s** the way it is supposed to **b**e

Also, I noticed it is different from the README and the CHANGELOG, I'm not sure why but would be interested to know.

**Comment by Schahen** [comment]
Thanks! I promise to be more careful.
Those shameful typos be gone in tomorrow's release.

**Comment by Schahen** [comment]
So let's actually discuss. Basically I want to keep CHANGELOG.md as succinct as possible (and README.md basically just mirrors the part of changelog).
Release notes on the other hand can cover everything in a more thorough fashion if needed. 
I suggest to do the following: let's put link to the the release notes in the changelog.

**Comment by LouisCAD** [comment]
No pressure for that, you can edit GitHub releases (although can't edit reads by people 😅).

Is there any particular reason you want to keep CHANGELOG.md as succint as possible?
As a library maintainer, I copy paste the content of the sufficiently (but not overly) detailed changelog to the GitHub releases, so the changes are also part of the git repository, even offline if cloned.
