### ISSUE TITLE
@@ArraySugar

### ISSUE THREAD

**Issue by ts2kt** [Kotlin/dukat#6]
```typescript
export type Headers = { [key: string]: string | string[] };
```
produce:
```kotlin
external interface Headers {
    @nativeGetter
    operator fun get(key: String): dynamic /* String | @@ArraySugar<String> */
    @nativeSetter
    operator fun set(key: String, value: String)
    @nativeSetter
    operator fun set(key: String, value: @@ArraySugar<String>)
}                                    //  ^
                                     //  | Error: Expected annotation identifier after '@'
```
Also `Unresolved reference: ArraySugar`
Also `@nativeGetter` and `@nativeSetter` marked as deprecated

**Comment by Schahen** [comment]
as of `Also @nativeGetter and @nativeSetter marked as deprecated` - I'll create a separate issue, as of this one - it's a bug and it's planned to be fix till next Friday release

**Comment by Schahen** [comment]
Github is closing this tasks automatically if specific text pattern is found in commit message.
I'd rather close this when npm package will be published.

**Comment by ts2kt** [comment]
@Schahen `@nativeGetter` and `@nativeSetter`still exist
```typescript
interface ResourceKey {
    [key: string]: any;
}
```
```kotlin
external interface ResourceKey {
    @nativeGetter
    operator fun get(key: String): Any?
    @nativeSetter
    operator fun set(key: String, value: Any)
}
```
