### ISSUE TITLE
Overrides are not resolved for parent entities defined in different files

### ISSUE THREAD

**Issue by Schahen** [Kotlin/dukat#9]
If one external class implement interface from another file, there are no override modifier, because each file converted independently.

**Comment by ts2kt** [comment]
```
// file1.d.ts
export abstract class ParentClass {
    public prop: any;
}
```
```
// file2.d.ts
export class ChildClass extends ParentClass {
    prop: string;
}
```
produce:

```
// file1.kt
external open class ParentClass {
    open var prop: Any = definedExternally
}
```
```
// file2.kt
external open class ChildClass : ParentClass {
    open var prop: String = definedExternally
}
```

1. `prop` hides member of supertype `ParentClass` and needs `override` modifier
2. `ParentClass` should be `abstract` instead `open`

**Comment by Schahen** [comment]
As of abstract classes - here's the separate issue:
https://github.com/Kotlin/dukat/issues/37

As of missing override, here's another one
https://github.com/Kotlin/dukat/issues/40

both supposed to end up in Friday's 0.0.8 release
